# Generated by Django 5.2.14 on 2026-08-27 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(max_length=20, unique=True)),
                ('sender_name', models.CharField(max_length=100)),
                ('receiver_name', models.CharField(max_length=100)),
                ('origin', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('current_location', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('ORDER_RECEIVED', 'Order Received'), ('PICKED_UP', 'Picked Up'), ('IN_TRANSIT', 'In Transit'), ('AT_HUB', 'Arrived at Hub'), ('OUT_FOR_DELIVERY', 'Out for Delivery'), ('DELIVERED', 'Delivered')], default='ORDER_RECEIVED', max_length=30)),
                ('package_description', models.CharField(blank=True, max_length=200)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('estimated_delivery', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
