# Generated by Django 5.2.14 on 2026-08-28 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackingUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ORDER_RECEIVED', 'Order Received'), ('PICKED_UP', 'Picked Up'), ('IN_TRANSIT', 'In Transit'), ('AT_HUB', 'Arrived at Hub'), ('OUT_FOR_DELIVERY', 'Out for Delivery'), ('DELIVERED', 'Delivered')], max_length=30)),
                ('location', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('timestamp', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_updates', to='website.shipment')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
